# Form implementation generated from reading ui file 'c:\Users\kccistc\Desktop\ai_study_avr\05 QT\practice_pyqt\EX04-12\gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 282)
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Flat)
        self.lcdNumber.setProperty("intValue", 99199199)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblRed = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRed.sizePolicy().hasHeightForWidth())
        self.lblRed.setSizePolicy(sizePolicy)
        self.lblRed.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.lblRed.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lblRed.setText("")
        self.lblRed.setObjectName("lblRed")
        self.horizontalLayout.addWidget(self.lblRed)
        self.lblGreen = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGreen.sizePolicy().hasHeightForWidth())
        self.lblGreen.setSizePolicy(sizePolicy)
        self.lblGreen.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.lblGreen.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lblGreen.setText("")
        self.lblGreen.setObjectName("lblGreen")
        self.horizontalLayout.addWidget(self.lblGreen)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
