# Form implementation generated from reading ui file 'c:\Users\kccistc\Desktop\ai_study_avr\05 QT\practice_pyqt\EX04-22\gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(333, 353)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblBlock = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblBlock.setGeometry(QtCore.QRect(40, 40, 20, 20))
        self.lblBlock.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.lblBlock.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblBlock.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lblBlock.setText("")
        self.lblBlock.setObjectName("lblBlock")
        self.pushButton = myButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 140, 81, 26))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.raise_()
        self.lblBlock.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 333, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
from mybutton import myButton
